# Generated by Django 6.0.3 on 2026-06-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='providers/profile/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='providers/idproof/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
