# Generated by Django 6.0.3 on 2026-06-08 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('AC Repair', 'AC Repair'), ('Plumbing', 'Plumbing'), ('Cleaning', 'Cleaning'), ('Beauty', 'Beauty'), ('Spa', 'Spa'), ('Hair Care', 'Hair Care')], max_length=100)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
